# Generated by Django 5.0.7 on 2024-08-03 08:21

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='temp-slug', editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
