# Generated by Django 5.0.7 on 2024-08-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Economics', 'Economics'), ('Environment', 'Environment'), ('Science', 'Science'), ('Technology', 'Technology'), ('International Relations', 'International Relations'), ('History', 'History'), ('Indian Polity', 'Indian Polity'), ('Geography', 'Geography'), ('Current Affairs', 'Current Affairs'), ('Indian Society', 'Indian Society'), ('Governance', 'Governance'), ('Disaster Management', 'Disaster Management'), ('Internal Security', 'Internal Security'), ('Social Justice', 'Social Justice'), ('Agriculture', 'Agriculture'), ('General Science', 'General Science'), ('Indian Heritage', 'Indian Heritage'), ("PYQ's", "PYQ's")], default='General Science', max_length=50),
        ),
    ]
